### ISSUE TITLE
Missing Media Picture

### ISSUE THREAD

**Issue by va-lemon** [chamberlain2007/apple_tv_mrp#2]
Hi, is this integration supposed to return the currently playing media’s poster? The HA built-in Apple TV integration returns a link to a picture of the currently playing program in the entity_picture attribute. I have successfully connected to my Apple TV running latest OS 12 but it does not seem to be returning the currently playing program’s poster.

**Comment by chamberlain2007** [comment]
Unfortunately pyatv doesn't expose this in the same way as it used to so it isn't currently supported. My understanding of the MRP protocol is it separately sends artwork information messages now, instead of that being part of the player status. So it's trickier to get.
