### ISSUE TITLE
Apple TV MRP not available in HACS

### ISSUE THREAD

**Issue by P-Verbrugge** [chamberlain2007/apple_tv_mrp#3]
The documentation states that you should be able to install it using HACS. However, it seems like it is not available in HACS.

I would be nice to have it in HACS in case of updates, instead of having to install and update it manually.

**Comment by SeanPM5** [comment]
You have to add it as a custom repository I believe.

Instructions:
1. In HACS, click on the "Settings" tab on the far right
2. At the bottom of that Settings page you will see a "Custom Repositories" section
3. Copy and paste the GitHub link (https://github.com/chamberlain2007/apple_tv_mrp) into there, select "Integration" from the category dropdown, and hit save.
4. Now you can install it and update it through HACS

**Comment by P-Verbrugge** [comment]
@SeanPM5 Ah, thanks! That works.
